### ISSUE TITLE
Error trying to launch with 'LXD', unable to fetch ubuntu cloud image

### ISSUE THREAD

**Issue by zoeyfyi** [canonical/action-build#7]
Thanks for this helpful action!

My snap builds stopped working with the following error:

```
/usr/bin/sg lxd -c snapcraft
Launching a container.
An error occurred with the instance when trying to launch with 'LXD': Unable to fetch https://cloud-images.ubuntu.com/buildd/daily/bionic/20200728/bionic-server-cloudimg-amd64-lxd_combined.tar.gz: 404 Not Found.
Ensure that 'LXD' is setup correctly and try again.
##[error]The process '/usr/bin/sg' failed with exit code 2
```

I believe this happened some time between `Sat Aug 8 06:53:26 2020 +0100` and `Sat Aug 8 20:07:06 2020 +0100`.

I have a made a minimal repo with the issue (I ran `snapcraft init` and used the most minimal workflow example):
- [repo](https://github.com/mrbenshef/snapcraft-build-test)
- [workflow file](https://github.com/mrbenshef/snapcraft-build-test/blob/master/.github/workflows/main.yml)
- [failing run](https://github.com/mrbenshef/snapcraft-build-test/runs/962831350?check_suite_focus=true)

I have tried replicating this in VM's unsuccessfully; any ideas what this could be?

**Comment by jhenstridge** [comment]
It looks like the metadata in https://cloud-images.ubuntu.com/buildd/daily/streams/v1/com.ubuntu.cloud:daily:download.json is out of date with respect to the published images: the metadata hasn't been updated since 29th July, while the latest image is from 9th August.

This isn't something I can work around in the action, and it likely isn't something that can be worked around in Snapcraft or LXD either.  I'll leave the bug report open until the problem is resolved though.

**Comment by zoeyfyi** [comment]
Looks like this has been resolved
